    document.write("<h2>Usuario:</h2>")
    let user=prompt("Tu nombre:")
    document.write(user)
    document.write("<br>")

    let a=prompt("Tu edad es:")
    document.write("Tiene "+a+" años.")
    document.write("<br>")
    let year=prompt("El año actual es:")
    document.write("Año: "+year)
    document.write("<br>")
    document.write("El año de nacimiento es: "+(year-a))

    document.write("<br>")
    document.write("<br>")
    document.write("Usuario 2 tiene "+(year-2000)+" años.")
    document.write("<br>")
    document.write("<br>")
    document.write("Usuario 3 tiene "+(year-1995)+" años.")
    document.write("<br>")
    document.write("<br>")
    document.write("Usuario 4 tiene "+(year-1990)+" años.")
    document.write("<br>")
    document.write("<br>")
